[build]
  command = "npm run build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "20.10.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_API_KEY_SUPERMAN = "ca05df74b569fe0aab3a3807ac61752c42f73f088"
  NEXT_PUBLIC_API_KEY_STONNER = "217fd46a6ccbbe5b586e8c25431e7699cf17abe351bbd330661acdb00de183"
  NEXT_PUBLIC_API_KEY_WARRIOR = "ade86ca71b794e2249f206f80905c6999ecd1191efe74"
  NEXT_PUBLIC_API_KEY_NOSFERATU = "7a2ef739e7612ad0ee0a88703ab61425eca82a442296de653d1d8578"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
